import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import { useBooking } from '../context/BookingContext';
import TicketApprovalTimer from './TicketApprovalTimer';
import { 
  CheckCircle2, Download, QrCode, XCircle, 
  ShieldCheck, MapPin, Clock, User, 
  Sparkles, AlertCircle, Wifi, Zap, Coffee
} from 'lucide-react';

export default function TicketConfirmation() {
  const { language, t, activeTicket, userBookings, setCurrentView, cancelUserTicket, approveTicket } = useBooking();
  const [showCancelModal, setShowCancelModal] = useState(false);
  const [isCancelled, setIsCancelled] = useState(false);
  const [autoGeneratedNotice, setAutoGeneratedNotice] = useState(true);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const ticket = activeTicket || userBookings[0];

  useEffect(() => {
    const timer = setTimeout(() => {
      setAutoGeneratedNotice(false);
    }, 5000);
    return () => clearTimeout(timer);
  }, []);

  if (!ticket) {
    return (
      <div className="max-w-4xl mx-auto py-12 px-4 text-center">
        <p className="text-slate-600 dark:text-slate-400 font-semibold">
          {language === 'kn' ? 'ಯಾವುದೇ ಸಕ್ರಿಯ ಟಿಕೆಟ್ ಕಂಡುಬಂದಿಲ್ಲ.' : 'No active ticket found.'}
        </p>
        <button
          onClick={() => setCurrentView('home')}
          className="mt-4 px-4 py-2 bg-[#0F4C81] text-white rounded-md text-xs font-black cursor-pointer"
        >
          {t.nav.home}
        </button>
      </div>
    );
  }

  // Download strict single A4 page PDF Ticket directly into Chrome Downloads
  const handleDownloadPdf = () => {
    try {
      setIsGeneratingPdf(true);
      const fileName = `Malenadu_Ticket_${ticket?.pnr || 'BUS'}.pdf`;

      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const pw = pdf.internal.pageSize.getWidth(); // 210mm

      // Header Banner (Dark Green #0B4F37)
      pdf.setFillColor(11, 79, 55);
      pdf.rect(10, 10, pw - 20, 28, 'F');

      // Accent Gold Border Line (#D48B16)
      pdf.setFillColor(212, 139, 22);
      pdf.rect(10, 38, pw - 20, 2, 'F');

      // Header Title
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(15);
      pdf.setFont('helvetica', 'bold');
      pdf.text('MALENADU TRAVELS PRIVATE LIMITED', 15, 22);

      pdf.setFontSize(8);
      pdf.setTextColor(245, 158, 11);
      pdf.text('OFFICIAL PASSENGER TRAVEL E-VOUCHER & BOARDING PASS', 15, 27);

      pdf.setTextColor(203, 213, 225);
      pdf.setFontSize(7);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Govt Regd Operator • ISO 9001:2025 Certified Fleet', 15, 33);

      // PNR Number Badge Box
      pdf.setTextColor(245, 158, 11);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'bold');
      pdf.text('PNR NUMBER', pw - 55, 20);

      pdf.setFontSize(13);
      pdf.setFont('courier', 'bold');
      pdf.text(String(ticket?.pnr || 'MAL-KN-001'), pw - 55, 27);

      pdf.setFontSize(7);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(255, 255, 255);
      pdf.text(`Booking ID: ${ticket?.bookingId || 'BK-1001'}`, pw - 55, 33);

      // Status Bar Box
      pdf.setFillColor(248, 250, 252);
      pdf.setDrawColor(203, 213, 225);
      pdf.rect(10, 44, pw - 20, 16, 'FD');

      pdf.setTextColor(15, 76, 129);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'bold');
      pdf.text('BUS SERVICE & COACH TYPE', 15, 50);

      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(11);
      pdf.text(String(ticket?.busName || 'Malenadu Luxury Bus'), 15, 56);

      pdf.setTextColor(33, 150, 243);
      pdf.setFontSize(8);
      pdf.text(`Registration: ${ticket?.busNo || 'KA-14-F-9900'}`, 110, 56);

      // Ticket Status Badge
      const statusText = String(ticket?.status || 'Confirmed');
      if (statusText.toLowerCase().includes('cancel')) {
        pdf.setFillColor(239, 68, 68);
        pdf.setTextColor(255, 255, 255);
        pdf.rect(pw - 55, 48, 45, 8, 'F');
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'bold');
        pdf.text('CANCELLED', pw - 48, 53);
      } else if (statusText.toLowerCase().includes('pending')) {
        pdf.setFillColor(245, 158, 11);
        pdf.setTextColor(255, 255, 255);
        pdf.rect(pw - 55, 48, 45, 8, 'F');
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'bold');
        pdf.text('PENDING APPROVAL', pw - 52, 53);
      } else {
        pdf.setFillColor(0, 200, 150);
        pdf.setTextColor(255, 255, 255);
        pdf.rect(pw - 55, 48, 45, 8, 'F');
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'bold');
        pdf.text('VERIFIED & ISSUED', pw - 52, 53);
      }

      // SECTION 2: PASSENGER MANIFEST TABLE
      pdf.setFillColor(15, 76, 129);
      pdf.rect(10, 64, pw - 20, 7, 'F');

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');
      pdf.text('PASSENGER MANIFEST & SEAT BREAKDOWN', 14, 69);

      // Table Header
      pdf.setFillColor(241, 245, 249);
      pdf.rect(10, 71, pw - 20, 7, 'F');
      pdf.setTextColor(71, 85, 105);
      pdf.setFontSize(8);
      pdf.text('PASSENGER NAME', 14, 76);
      pdf.text('SEAT(S)', 80, 76);
      pdf.text('FARE PER SEAT', 125, 76);
      pdf.text('TOTAL AMOUNT', 165, 76);

      // Table Row 1
      pdf.setFillColor(255, 255, 255);
      pdf.rect(10, 78, pw - 20, 10, 'F');
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');
      pdf.text(String(ticket?.passengerName || 'Traveler'), 14, 84);

      const seatsStr = Array.isArray(ticket?.seats) ? ticket.seats.join(', ') : String(ticket?.seats || 'Seat 1');
      pdf.setTextColor(15, 76, 129);
      pdf.text(seatsStr, 80, 84);

      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`₹${ticket?.amountPaid || ticket?.amount || 0}`, 125, 84);

      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(16, 185, 129);
      pdf.text(`₹${ticket?.amountPaid || ticket?.amount || 0}`, 165, 84);

      // SECTION 3: TRIP SCHEDULE GRID
      pdf.setFillColor(15, 76, 129);
      pdf.rect(10, 93, pw - 20, 7, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');
      pdf.text('TRIP SCHEDULE & BOARDING DETAILS', 14, 98);

      pdf.setFillColor(248, 250, 252);
      pdf.setDrawColor(226, 232, 240);
      pdf.rect(10, 100, pw - 20, 32, 'FD');

      // Origin
      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(7);
      pdf.text('ORIGIN / DEPARTURE', 15, 106);
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text(String(ticket?.from || 'Bengaluru'), 15, 112);

      // Destination
      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(7);
      pdf.text('DESTINATION / ARRIVAL', 110, 106);
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text(String(ticket?.to || 'Shivamogga'), 110, 112);

      // Departure Date & Time
      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(7);
      pdf.text('TRAVEL DATE', 15, 122);
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(9);
      pdf.text(String(ticket?.journeyDate || 'Today'), 15, 127);

      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(7);
      pdf.text('DEPARTURE TIME', 110, 122);
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(9);
      pdf.text(String(ticket?.departureTime || '10:00 PM'), 110, 127);

      // SECTION 4: DIGITAL CONDUCTOR SCAN PASS
      pdf.setFillColor(15, 23, 42);
      pdf.rect(10, 136, pw - 20, 25, 'F');

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.text('DIGITAL CONDUCTOR VERIFICATION PASS', 15, 144);

      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(203, 213, 225);
      pdf.text('Present this QR code or PNR voucher to conductor upon boarding.', 15, 150);
      pdf.text(`Verification Code: ${ticket?.pnr || 'PNR'}-VERIFIED-PASS`, 15, 155);

      pdf.setFillColor(0, 200, 150);
      pdf.rect(pw - 55, 144, 45, 10, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'bold');
      pdf.text('VERIFIED FLEET', pw - 48, 150);

      // SECTION 5: PASSENGER TERMS
      pdf.setFillColor(255, 251, 235);
      pdf.setDrawColor(253, 230, 138);
      pdf.rect(10, 165, pw - 20, 24, 'FD');

      pdf.setTextColor(146, 64, 14);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'bold');
      pdf.text('IMPORTANT PASSENGER GUIDELINES & RULES:', 14, 171);

      pdf.setFontSize(7);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(120, 53, 15);
      pdf.text('• Reporting time: 15 minutes prior to departure at boarding terminal.', 14, 176);
      pdf.text('• Carry valid photo ID (Aadhaar, Passport, Driving License, Voter ID).', 14, 180);
      pdf.text('• Free luggage allowance up to 15kg per passenger.', 14, 184);
      pdf.text('• 24x7 Customer Support: 1800 425 0022 / support@malenadutravels.com', 14, 188);

      // FOOTER
      pdf.setDrawColor(226, 232, 240);
      pdf.line(10, 193, pw - 10, 193);

      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(7);
      pdf.text('© 2026 Malenadu Travels Private Limited. Official 1-Page E-Ticket Pass.', 14, 198);
      pdf.text('System Generated E-Voucher • Valid Without Physical Signature.', 14, 202);

      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(16, 185, 129);
      pdf.text('Authorized & Validated ✓', pw - 55, 200);

      // Trigger instant browser download into Chrome Downloads
      pdf.save(fileName);
      setIsGeneratingPdf(false);
    } catch (err) {
      console.error('Vector PDF creation error:', err);
      setIsGeneratingPdf(false);
    }
  };

  const handleShareWhatsApp = () => {
    const text = `🎉 *Malenadu Travels Official E-Ticket*\nPNR: ${ticket.pnr}\nPassenger: ${ticket.passengerName}\nBus: ${ticket.busName} (${ticket.busNo})\nSeats: ${ticket.seats?.join(', ')}\nJourney: ${ticket.from} ➔ ${ticket.to}\nDate: ${ticket.journeyDate} (${ticket.departureTime})\nStatus: CONFIRMED & ISSUED 🚌`;
    window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`, '_blank');
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 print:p-0 print:m-0 print:max-w-none">
      
      {/* Notice Banner (Hidden in Print) */}
      {autoGeneratedNotice && (
        <div className="mb-6 p-4 rounded-md bg-[#00C896]/10 border-2 border-[#00C896]/40 text-[#0F4C81] dark:text-[#00C896] font-black text-xs sm:text-sm flex items-center justify-between shadow-lg print:hidden">
          <div className="flex items-center space-x-2">
            <CheckCircle2 className="w-5 h-5 text-[#00C896] shrink-0" />
            <span>{language === 'kn' ? 'ಅಧಿಕೃತ ಇ-ಟಿಕೆಟ್ ಸಿದ್ಧವಾಗಿದೆ! ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಕೆಳಗಿನ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.' : "Official E-Ticket Ready! Click 'Download 1-Page PDF' for your A4 ticket."}</span>
          </div>
          <button onClick={() => setAutoGeneratedNotice(false)} className="text-slate-400 hover:text-slate-600 font-bold ml-2">✕</button>
        </div>
      )}

      {/* IF CANCELLED OR REJECTED SHOW CANCELLED NOTICE BANNER */}
      {(isCancelled || ticket.status === 'Cancelled' || ticket.status === 'Cancelled by Admin' || ticket.status === 'Rejected') ? (
        <div className="w-full max-w-[800px] mx-auto bg-slate-900 text-white rounded-lg border-2 border-red-500/50 shadow-2xl p-6 sm:p-8 space-y-6 text-center print:hidden">
          <div className="w-16 h-16 rounded-full bg-red-500/20 text-red-400 border-2 border-red-500/40 flex items-center justify-center mx-auto shadow-xl">
            <XCircle className="w-9 h-9 text-red-400" />
          </div>

          <div className="space-y-2">
            <span className="px-3 py-1 rounded-md text-xs font-black bg-red-500/20 text-red-300 border border-red-500/40 uppercase tracking-wider">
              {language === 'kn' ? 'ಟಿಕೆಟ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ / ನಿರಾಕರಿಸಲಾಗಿದೆ' : 'Ticket Booking Cancelled / Rejected'}
            </span>
            <h2 className="text-2xl sm:text-3xl font-black text-white pt-1">
              {language === 'kn' ? 'ಈ ಟಿಕೆಟ್‌ ರದ್ದಾಗಿದೆ' : 'This Ticket Booking Has Been Cancelled'}
            </h2>
            <p className="text-xs text-red-300 font-semibold max-w-xl mx-auto leading-relaxed">
              {language === 'kn' 
                ? `ನಿಮ್ಮ ಟಿಕೆಟ್ ಕಾಯ್ದಿರಿಸುವಿಕೆಯನ್ನು (PNR: ${ticket.pnr}) ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ. ಪಾವತಿಸಿದ ಹಣವನ್ನು 24 ಗಂಟೆಗಳ ಒಳಗೆ ನಿಮ್ಮ ಖಾತೆಗೆ ಹಿಂತಿರುಗಿಸಲಾಗುತ್ತದೆ.` 
                : `This ticket booking request (PNR: ${ticket.pnr}) was cancelled. Paid amount ₹${ticket.amountPaid || ticket.amount || 0} will be refunded within 24 hours.`}
            </p>
          </div>

          {/* Cancelled Details Card */}
          <div className="p-5 rounded-md bg-slate-800/90 border border-slate-700 text-left space-y-3">
            <div className="flex justify-between items-center pb-3 border-b border-slate-700">
              <span className="text-xs font-black text-red-400 font-mono">PNR: {ticket.pnr}</span>
              <span className="text-xs font-black text-slate-400">Booking ID: {ticket.bookingId}</span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ಪ್ರಯಾಣಿಕರು' : 'Passenger'}</span>
                <span className="font-black text-white">{ticket.passengerName || 'Passenger'}</span>
              </div>
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ಬಸ್ ಸೇವೆ' : 'Bus Service'}</span>
                <span className="font-black text-white">{ticket.busName}</span>
              </div>
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ಮಾರ್ಗ' : 'Route'}</span>
                <span className="font-black text-white">{ticket.from} ➔ {ticket.to}</span>
              </div>
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ರಿಫಂಡ್ ಹಣ' : 'Refund Status'}</span>
                <span className="font-black text-emerald-400 text-sm">₹{ticket.amountPaid || ticket.amount || 0} (Refunded)</span>
              </div>
            </div>
          </div>

          <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-3">
            <button
              onClick={() => {
                setCurrentView('search-results');
                window.scrollTo({ top: 0, behavior: 'smooth' });
              }}
              className="px-6 py-3 rounded-md bg-gradient-to-r from-emerald-600 to-teal-600 text-white font-black text-xs shadow-lg hover:scale-105 transition-all cursor-pointer"
            >
              🚍 {language === 'kn' ? 'ಮತ್ತೊಂದು ಬಸ್ ಕಾಯ್ದಿರಿಸಿ' : 'Book Another Bus Service'}
            </button>
            
            <button
              onClick={() => {
                setCurrentView('home');
                window.scrollTo({ top: 0, behavior: 'smooth' });
              }}
              className="px-6 py-3 rounded-md bg-slate-800 text-slate-300 hover:text-white font-black text-xs border border-slate-700 transition-all cursor-pointer"
            >
              🏠 {t.nav.home}
            </button>
          </div>
        </div>
      ) : (ticket.status === 'Pending Admin Approval' || ticket.status === 'Pending Approval') ? (
        /* IF PENDING ADMIN APPROVAL: SHOW AWAITING ADMIN APPROVAL CARD */
        <div id="pending-printable-ticket" className="w-full max-w-[800px] mx-auto bg-slate-900 text-white rounded-2xl border-2 border-amber-500/50 shadow-2xl p-6 sm:p-8 space-y-6 text-center print:hidden">
          <div className="w-16 h-16 rounded-full bg-amber-500/20 text-amber-400 border-2 border-amber-500/40 flex items-center justify-center mx-auto shadow-xl animate-pulse">
            <Clock className="w-9 h-9 text-amber-400" />
          </div>

          <div className="space-y-2">
            <span className="px-3.5 py-1 rounded-full text-xs font-black bg-amber-500/20 text-amber-300 border border-amber-500/40 uppercase tracking-wider">
              ⏳ {language === 'kn' ? 'ಅಡ್ಮಿನ್ ಅನುಮೋದನೆಗೆ ಕಾಯುತ್ತಿದೆ' : 'Awaiting Admin Approval'}
            </span>
            <h2 className="text-2xl sm:text-3xl font-black text-white pt-1">
              {t.ticket.pendingApproval}
            </h2>
            <p className="text-xs text-amber-300 font-semibold max-w-xl mx-auto leading-relaxed">
              {t.ticket.pendingSubtitle}
            </p>
          </div>

          {/* Live Timer Card */}
          <div className="flex justify-center pt-1">
            <TicketApprovalTimer autoApproveAt={ticket.autoApproveAt} status={ticket.status} className="scale-110" />
          </div>

          {/* Pending Summary Card */}
          <div className="p-5 rounded-xl bg-slate-800/90 border border-slate-700 text-left space-y-3">
            <div className="flex justify-between items-center pb-3 border-b border-slate-700">
              <span className="text-xs font-black text-amber-400 font-mono">PNR: {ticket.pnr}</span>
              <span className="text-xs font-black text-slate-400">Booking ID: {ticket.bookingId}</span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ಪ್ರಯಾಣಿಕರು' : 'Passenger'}</span>
                <span className="font-black text-white">{ticket.passengerName}</span>
              </div>
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ಬಸ್ ಸೇವೆ' : 'Bus Service'}</span>
                <span className="font-black text-white">{ticket.busName}</span>
              </div>
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ಮಾರ್ಗ' : 'Route'}</span>
                <span className="font-black text-white">{ticket.from} ➔ {ticket.to}</span>
              </div>
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 block">{language === 'kn' ? 'ಪಾವತಿಸಿದ ದರ' : 'Fare Paid'}</span>
                <span className="font-black text-emerald-400 text-sm">₹{ticket.amountPaid}</span>
              </div>
            </div>
          </div>

          <div className="flex flex-wrap justify-center gap-3 pt-2">
            <button
              onClick={() => setShowCancelModal(true)}
              className="px-6 py-3.5 rounded-xl bg-red-600/90 hover:bg-red-600 text-white text-xs font-black flex items-center space-x-2 shadow-xl hover:scale-105 transition-all cursor-pointer border border-red-400/40"
            >
              <XCircle className="w-4 h-4 text-red-200" />
              <span>{language === 'kn' ? 'ಬುಕಿಂಗ್ ರದ್ದುಗೊಳಿಸಿ' : 'Cancel Booking'}</span>
            </button>
          </div>

          <div className="pt-2 text-[11px] text-slate-400 font-semibold">
            ℹ️ {language === 'kn' ? 'ಅಡ್ಮಿನ್ ಅನುಮೋದಿಸಿದ ತಕ್ಷಣ ನಿಮ್ಮ ಅಧಿಕೃತ ೧-ಪುಟದ ಇ-ಟಿಕೆಟ್ ಮತ್ತು ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಇಲ್ಲೇ ಕಾಣಿಸುತ್ತದೆ.' : 'Your official 1-Page A4 Boarding Pass & PDF Download button will be unlocked here automatically once approved by Admin.'}
          </div>
        </div>
      ) : (
        <>
          {/* Top Status & Action Bar when Confirmed/Approved */}
          <div className="p-6 sm:p-8 rounded-2xl mb-8 border border-slate-800 text-center relative overflow-hidden bg-slate-900 text-white shadow-2xl print:hidden">
            <div className="space-y-2">
              <div className="w-14 h-14 rounded-full bg-[#00C896] text-white flex items-center justify-center mx-auto mb-2 shadow-xl shadow-[#00C896]/30 animate-bounce">
                <CheckCircle2 className="w-8 h-8" />
              </div>
              <h2 className="text-2xl sm:text-3xl font-black text-white mb-1">
                {t.ticket.confirmed}
              </h2>
            </div>

            {/* Direct PDF Download & Cancel Action Buttons */}
            <div className="flex flex-wrap justify-center gap-3 mt-5">
              <button
                onClick={handleDownloadPdf}
                disabled={isGeneratingPdf}
                className="px-8 py-4 rounded-2xl bg-[#0B4F37] hover:bg-[#063925] text-amber-300 text-sm sm:text-base font-black flex items-center space-x-3 shadow-2xl shadow-emerald-900/50 hover:scale-105 transition-all cursor-pointer border-2 border-amber-400/40"
              >
                <Download className="w-6 h-6 text-amber-400" />
                <span>
                  {isGeneratingPdf 
                    ? (language === 'kn' ? 'ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...' : 'Downloading PDF File...') 
                    : (language === 'kn' ? '📥 ಪಿಡಿಎಫ್ ಟಿಕೆಟ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (.pdf)' : '📥 DOWNLOAD DIRECT PDF TICKET (.pdf)')
                  }
                </span>
              </button>

              <button
                onClick={() => setShowCancelModal(true)}
                className="px-6 py-4 rounded-2xl bg-red-600/90 hover:bg-red-600 text-white text-sm font-black flex items-center space-x-2 shadow-xl hover:scale-105 transition-all cursor-pointer border border-red-400/40"
              >
                <XCircle className="w-5 h-5 text-red-200" />
                <span>{language === 'kn' ? 'ಟಿಕೆಟ್ ರದ್ದುಗೊಳಿಸಿ' : 'Cancel Booking'}</span>
              </button>
            </div>
          </div>

          {/* STRICT 1-PAGE A4 PRINTABLE TICKET CONTAINER */}
          <div 
            id="printable-ticket" 
            style={{ backgroundColor: '#ffffff', color: '#0f172a' }}
            className="w-full max-w-[800px] mx-auto min-h-[960px] max-h-[1050px] bg-white text-slate-900 rounded-md border-4 border-[#0B4F37] shadow-2xl flex flex-col justify-between overflow-hidden p-5 sm:p-6 space-y-4 print:border-2 print:border-[#0B4F37] print:shadow-none print:rounded-none print:p-0 print:m-0 print:h-[285mm] print:max-h-[285mm]"
          >
        
        {/* SECTION 1: HEADER BRAND BAR */}
        <div className="space-y-3">
          <div 
            style={{ backgroundColor: '#0B4F37', color: '#ffffff' }}
            className="p-4 sm:p-5 rounded-md text-white flex flex-wrap justify-between items-center gap-3 shadow-md border-b-4 border-[#D48B16]"
          >
            <div className="flex items-center space-x-3">
              <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-full overflow-hidden border-2 border-[#D48B16] bg-slate-950 shrink-0">
                <img 
                  src="/malenadu_circle_logo.jpg" 
                  alt="Malenadu Travels Logo" 
                  className="w-full h-full object-cover"
                  onError={(e) => { e.target.style.display = 'none'; }}
                />
              </div>
              <div>
                <h1 className="font-black text-lg sm:text-xl tracking-tight text-white uppercase leading-none">
                  Malenadu Travels Private Limited
                </h1>
                <p className="text-[10px] text-[#F59E0B] font-extrabold uppercase tracking-widest mt-1">
                  {language === 'kn' ? 'ಅಧಿಕೃತ ಪ್ರಯಾಣಿಕರ ಇ-ಟಿಕೆಟ್ ಮತ್ತು ಬೋರ್ಡಿಂಗ್ ಪಾಸ್' : 'OFFICIAL PASSENGER TRAVEL E-VOUCHER & BOARDING PASS'}
                </p>
                <p className="text-[9px] text-slate-300 font-semibold mt-0.5">
                  {language === 'kn' ? 'ಸರ್ಕಾರಿ ನೋಂದಾಯಿತ ಸಂಸ್ಥೆ • ISO 9001:2025 ಪ್ರಮಾಣೀಕೃತ' : 'Govt Regd Operator • ISO 9001:2025 Certified Fleet'}
                </p>
              </div>
            </div>

            <div className="text-right border-l-2 border-white/20 pl-3">
              <p className="text-[9px] font-black text-slate-300 uppercase tracking-widest">{t.ticket.pnr}</p>
              <p className="text-lg sm:text-xl font-black font-mono tracking-wider text-[#F59E0B]">{ticket.pnr}</p>
              <p className="text-[9px] text-slate-200 font-bold">{language === 'kn' ? 'ಬುಕಿಂಗ್ ಐಡಿ' : 'Booking ID'}: {ticket.bookingId}</p>
            </div>
          </div>

          {/* STATUS & BUS OVERVIEW BAR */}
          <div 
            style={{ backgroundColor: '#f8fafc', borderColor: '#cbd5e1' }}
            className="p-3.5 rounded-md border-2 flex flex-wrap justify-between items-center gap-2 text-xs"
          >
            <div>
              <span className="text-[9.5px] font-black text-[#0F4C81] uppercase tracking-wider block">
                {language === 'kn' ? 'ಬಸ್ ಕೋಚ್ ಮತ್ತು ಸೇವಾ ಹೆಸರು' : 'Bus Coach & Service Name'}
              </span>
              <p className="text-base font-black text-slate-900">{ticket.busName}</p>
              <p className="text-xs font-black text-[#2196F3]">{language === 'kn' ? 'ಬಸ್ ನೋಂದಣಿ ಸಂಖ್ಯೆ' : 'Coach Registration No'}: {ticket.busNo}</p>
            </div>

            <div className="flex items-center space-x-3">
              <div className="text-right">
                <TicketApprovalTimer autoApproveAt={ticket.autoApproveAt} status={ticket.status} />
                <p className="text-[9.5px] font-black text-slate-600 mt-1">
                  {language === 'kn' ? 'ಪಾವತಿ ಸ್ಥಿತಿ: ಪಾವತಿಸಲಾಗಿದೆ ಮತ್ತು ಪರಿಶೀಲಿಸಲಾಗಿದೆ' : 'Payment Status: Paid & Digitally Verified'}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* SECTION 2: PASSENGER & FARE DETAILS GRID */}
        <div className="space-y-2.5">
          <h3 className="text-[11px] font-black text-[#0F4C81] uppercase tracking-widest border-b-2 border-[#0F4C81]/30 pb-0.5 flex items-center gap-1.5">
            <User className="w-3.5 h-3.5 text-[#00C896]" />
            <span>{language === 'kn' ? 'ಪ್ರಯಾಣಿಕರ ಪಟ್ಟಿ ಮತ್ತು ದರ ವಿವರ' : 'Passenger Manifest & Fare Breakdown'}</span>
          </h3>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
            <div style={{ backgroundColor: '#eff6ff', borderColor: '#bfdbfe' }} className="p-3 rounded-md border-2">
              <p className="text-[8.5px] text-[#0F4C81] font-black uppercase tracking-wider">
                {language === 'kn' ? 'ಮುಖ್ಯ ಪ್ರಯಾಣಿಕರು' : 'Primary Passenger'}
              </p>
              <p className="text-xs font-black text-slate-900 mt-0.5">{ticket.passengerName}</p>
              <p className="text-[10px] text-slate-700 font-bold">{ticket.mobile}</p>
              <p className="text-[9px] text-slate-500 font-semibold">{ticket.email}</p>
            </div>

            <div style={{ backgroundColor: '#eff6ff', borderColor: '#bfdbfe' }} className="p-3 rounded-md border-2">
              <p className="text-[8.5px] text-[#0F4C81] font-black uppercase tracking-wider">
                {language === 'kn' ? 'ದಿನಾಂಕ ಮತ್ತು ಸಮಯ' : 'Date & Departure'}
              </p>
              <p className="text-xs font-black text-slate-900 mt-0.5">{ticket.journeyDate}</p>
              <p className="text-[10px] font-black text-[#0F4C81]">
                {language === 'kn' ? 'ಹೊರಡುವ ಸಮಯ' : 'Dep. Time'}: {ticket.departureTime}
              </p>
              <p className="text-[9px] text-slate-500 font-semibold">
                {language === 'kn' ? '೧೫ ನಿಮಿಷ ಮುಂಚಿತವಾಗಿ ಬನ್ನಿ' : 'Reporting: 15 Mins Prior'}
              </p>
            </div>

            <div style={{ backgroundColor: '#eff6ff', borderColor: '#bfdbfe' }} className="p-3 rounded-md border-2">
              <p className="text-[8.5px] text-[#0F4C81] font-black uppercase tracking-wider">
                {language === 'kn' ? 'ಆಸನ ಸಂಖ್ಯೆಗಳು' : 'Seat Number(s)'}
              </p>
              <p className="text-xs font-black text-[#00C896] mt-0.5">{ticket.seats?.join(', ')}</p>
              <p className="text-[10px] text-slate-700 font-bold">
                {ticket.seats?.length} {language === 'kn' ? 'ಆಸನಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ' : 'Seat(s) Reserved'}
              </p>
              <p className="text-[9px] text-slate-500 font-semibold">
                {language === 'kn' ? 'ಮಾದರಿ: ಐಷಾರಾಮಿ ಕೋಚ್' : 'Type: AC Sleeper/Seater'}
              </p>
            </div>

            <div style={{ backgroundColor: '#ecfdf5', borderColor: '#a7f3d0' }} className="p-3 rounded-md border-2">
              <p className="text-[8.5px] text-emerald-900 font-black uppercase tracking-wider">
                {language === 'kn' ? 'ಒಟ್ಟು ಪಾವತಿಸಿದ ದರ' : 'Total Fare Paid'}
              </p>
              <p className="text-sm font-black text-[#00C896] mt-0.5">₹{ticket.amountPaid}</p>
              <p className="text-[10px] text-emerald-800 font-bold">
                {language === 'kn' ? 'ಜಿಎಸ್‌ಟಿ ಮತ್ತು ವಿಮೆ ಸೇರಿದೆ' : 'GST & Insurance Included'}
              </p>
              <p className="text-[9px] text-emerald-700 font-semibold">
                {language === 'kn' ? 'ಯಾವುದೇ ಹೆಚ್ಚುವರಿ ಶುಲ್ಕವಿಲ್ಲ' : 'Zero Extra Fee'}
              </p>
            </div>
          </div>
        </div>

        {/* SECTION 3: BOARDING & DROPPING TERMINAL MAP */}
        <div className="space-y-2.5">
          <h3 className="text-[11px] font-black text-[#0F4C81] uppercase tracking-widest border-b-2 border-[#0F4C81]/30 pb-0.5 flex items-center gap-1.5">
            <MapPin className="w-3.5 h-3.5 text-[#00C896]" />
            <span>{language === 'kn' ? 'ಪ್ರಯಾಣ ಮಾರ್ಗ ಮತ್ತು ಟರ್ಮಿನಲ್' : 'Journey Route & Terminal Schedule'}</span>
          </h3>

          <div style={{ backgroundColor: '#f0f9ff', borderColor: '#bae6fd' }} className="p-4 rounded-md border-2 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs">
            <div className="space-y-0.5 text-center sm:text-left flex-1">
              <span className="inline-block px-2 py-0.5 rounded bg-[#0F4C81] text-white text-[8.5px] font-black uppercase">
                {language === 'kn' ? 'ಹತ್ತುವ ಸ್ಥಳ' : 'Boarding Point'}
              </span>
              <p className="font-black text-slate-900 text-sm sm:text-base">{ticket.from}</p>
              <p className="text-[10px] text-slate-700 font-bold">
                {language === 'kn' ? 'ಟರ್ಮಿನಲ್ ಗೇಟ್ #೧' : 'Terminal Gate #1'} • {language === 'kn' ? 'ಸಮಯ' : 'Time'}: {ticket.departureTime}
              </p>
            </div>

            <div className="text-center px-3 py-1.5 rounded-md bg-white border border-blue-200 shadow-sm flex flex-col items-center shrink-0">
              <span className="text-[9px] font-black text-emerald-600 uppercase tracking-widest">DIRECT EXPRESS</span>
              <div className="text-[#00C896] font-black text-xs my-0.5">━━━━ 🚌 ━━━━</div>
              <span className="text-[8.5px] font-bold text-slate-500">Karnataka Highway Corridor</span>
            </div>

            <div className="space-y-0.5 text-center sm:text-right flex-1">
              <span className="inline-block px-2 py-0.5 rounded bg-[#00C896] text-white text-[8.5px] font-black uppercase">
                {language === 'kn' ? 'ಇಳಿಯುವ ಸ್ಥಳ' : 'Dropping Point'}
              </span>
              <p className="font-black text-slate-900 text-sm sm:text-base">{ticket.to}</p>
              <p className="text-[10px] text-slate-700 font-bold">{language === 'kn' ? 'ತಲುಪುವ ಟರ್ಮಿನಲ್' : 'Destination Depot Terminal'}</p>
            </div>
          </div>
        </div>

        {/* SECTION 4: ONBOARD AMENITIES & CONDUCTOR QR PASS */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          
          {/* Amenities Box */}
          <div style={{ backgroundColor: '#f8fafc', borderColor: '#e2e8f0' }} className="p-3 rounded-md border-2 sm:col-span-1 space-y-1.5">
            <p className="text-[9.5px] font-black text-[#0F4C81] uppercase tracking-wider flex items-center gap-1">
              <Sparkles className="w-3 h-3 text-amber-500" />
              <span>{language === 'kn' ? 'ಉಚಿತ ಸೌಲಭ್ಯಗಳು' : 'Included Amenities'}</span>
            </p>
            <div className="grid grid-cols-2 gap-1.5 text-[10px] font-bold text-slate-700 pt-0.5">
              <div className="flex items-center gap-1">
                <Wifi className="w-3 h-3 text-blue-600" />
                <span>{language === 'kn' ? 'ಉಚಿತ ವೈಫೈ' : 'Free Wi-Fi'}</span>
              </div>
              <div className="flex items-center gap-1">
                <Zap className="w-3 h-3 text-amber-500" />
                <span>{language === 'kn' ? 'ಚಾರ್ಜಿಂಗ್' : 'Charging'}</span>
              </div>
              <div className="flex items-center gap-1">
                <Coffee className="w-3 h-3 text-emerald-600" />
                <span>{language === 'kn' ? 'ಕುಡಿಯುವ ನೀರು' : 'Water'}</span>
              </div>
              <div className="flex items-center gap-1">
                <ShieldCheck className="w-3 h-3 text-indigo-600" />
                <span>{language === 'kn' ? 'ಜಿಪಿಎಸ್' : 'Live GPS'}</span>
              </div>
            </div>
          </div>

          {/* Conductor Verification Pass */}
          <div style={{ backgroundColor: '#0f172a', color: '#ffffff' }} className="p-3.5 rounded-md border-2 border-slate-800 sm:col-span-2 flex items-center justify-between gap-3 shadow-md">
            <div className="flex items-center space-x-3">
              <div className="p-1 bg-white rounded-md border border-[#00C896] shrink-0">
                <QrCode className="w-12 h-12 text-slate-900" />
              </div>
              <div>
                <p className="text-xs font-black text-white">{language === 'kn' ? 'ಡಿಜಿಟಲ್ ಕಂಡಕ್ಟರ್ ಸ್ಕ್ಯಾನ್ ಪಾಸ್' : 'Digital Conductor Scan Pass'}</p>
                <p className="text-[10px] text-slate-300 font-medium max-w-xs leading-tight">
                  {language === 'kn' ? 'ಬಸ್ ಹತ್ತುವಾಗ ಈ ಕ್ಯೂಆರ್ ಕೋಡ್ ಅಥವಾ ಪಿಎನ್‌ಆರ್ ತೋರಿಸಿ.' : 'Present this QR code or PNR voucher to conductor upon boarding.'}
                </p>
                <p className="text-[9px] text-[#00C896] font-black mt-0.5">Verification: {ticket.pnr}-VERIFIED</p>
              </div>
            </div>

            <div className="text-right shrink-0 border-l border-slate-700 pl-3">
              <p className="text-[8.5px] text-slate-400 font-bold uppercase">{language === 'kn' ? 'ಅಧಿಕೃತ ಮುದ್ರೆ' : 'Official Seal'}</p>
              <div className="mt-0.5 px-2.5 py-0.5 rounded-md bg-[#00C896] text-white font-black text-[9.5px] flex items-center space-x-1">
                <ShieldCheck className="w-3 h-3 text-white" />
                <span>{language === 'kn' ? 'ಪ್ರಮಾಣೀಕೃತ ಬಸ್' : 'Verified Fleet'}</span>
              </div>
            </div>
          </div>

        </div>

        {/* SECTION 5: IMPORTANT PASSENGER TERMS & POLICIES */}
        <div style={{ backgroundColor: '#fffbeb', borderColor: '#fde68a', color: '#78350f' }} className="p-3 rounded-md border-2 text-[9.5px] space-y-0.5 font-medium">
          <p className="font-black text-amber-900 uppercase tracking-wider text-[8.5px] flex items-center gap-1">
            <AlertCircle className="w-3 h-3 text-amber-600" />
            <span>{language === 'kn' ? 'ಪ್ರಮುಖ ಪ್ರಯಾಣಿಕರ ಮಾರ್ಗಸೂಚಿಗಳು ಮತ್ತು ನಿಯಮಗಳು:' : 'Important Passenger Guidelines & Rules:'}</span>
          </p>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-0.5 list-disc pl-4 text-amber-950 font-semibold">
            <li>{language === 'kn' ? 'ಹೊರಡುವ ಸಮಯಕ್ಕಿಂತ ೧೫ ನಿಮಿಷ ಮುಂಚಿತವಾಗಿ ವರದಿ ಮಾಡಿ.' : 'Reporting time: 15 minutes prior to departure at boarding terminal.'}</li>
            <li>{language === 'kn' ? 'ಮಾನ್ಯ ಗುರುತಿನ ಚೀಟಿ (ಆಧಾರ್, ಪಾಸ್‌ಪೋರ್ಟ್, ಚಾಲನಾ ಪರವಾನಗಿ) ತನ್ನಿ.' : 'Carry valid photo ID (Aadhaar, Passport, Driving License, Voter ID).'}</li>
            <li>{language === 'kn' ? 'ಪ್ರತಿ ಪ್ರಯಾಣಿಕರಿಗೆ ೧೫ ಕೆಜಿ ಉಚಿತ ಲಗೇಜ್ ಅವಕಾಶ.' : 'Free luggage allowance up to 15kg per passenger.'}</li>
            <li>{language === 'kn' ? '೨೪x೭ ಗ್ರಾಹಕ ನೆರವು: ೧೮೦೦ ೪೨೫ ೦೦೨೨' : '24x7 Customer Support: 1800 425 0022 / support@malenadutravels.com'}</li>
          </ul>
        </div>

        {/* SECTION 6: FOOTER OFFICIAL STAMP & SIGNATURE */}
        <div className="pt-2 border-t-2 border-slate-200 flex flex-wrap justify-between items-center text-[9px] text-slate-600 font-bold gap-2">
          <div>
            <p>© 2026 Malenadu Travels Private Limited. {language === 'kn' ? 'ಅಧಿಕೃತ ೧-ಪುಟದ ಇ-ಟಿಕೆಟ್.' : 'Official 1-Page E-Ticket Pass.'}</p>
            <p className="text-[8px] text-slate-400 font-medium">{language === 'kn' ? 'ಕಂಪ್ಯೂಟರ್ ಸೃಷ್ಟಿಸಿದ ವೋಚರ್ • ಸಹಿಯ ಅಗತ್ಯವಿಲ್ಲ' : 'System Generated E-Voucher • Valid Without Signature'}</p>
          </div>

          <div className="flex items-center space-x-3">
            <div className="text-right">
              <p className="text-[9px] font-black text-slate-800 uppercase">{language === 'kn' ? 'ಮಲೆನಾಡು ಆಡಳಿತ' : 'Malenadu Executive Seal'}</p>
              <p className="text-[8px] text-emerald-600 font-extrabold">{language === 'kn' ? 'ಅಧಿಕೃತವಾಗಿ ನೀಡಲಾಗಿದೆ' : 'Authorized & Validated'}</p>
            </div>
            <div className="w-8 h-8 rounded-full bg-emerald-100 border border-emerald-500 flex items-center justify-center text-emerald-700 font-black text-xs shadow-sm">
              ✓
            </div>
          </div>
        </div>

          </div>
        </>
      )}

      {/* CANCELLATION CONFIRMATION MODAL */}
      {showCancelModal && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-4 print:hidden animate-fade-in">
          <div className="bg-slate-900 text-white p-6 sm:p-8 rounded-3xl border-2 border-red-500/50 shadow-2xl max-w-md w-full text-center space-y-5">
            <div className="w-16 h-16 rounded-full bg-red-500/20 text-red-400 border border-red-500/40 flex items-center justify-center mx-auto shadow-lg">
              <XCircle className="w-9 h-9" />
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-black text-white">
                {language === 'kn' ? 'ಟಿಕೆಟ್ ಬುಕಿಂಗ್ ರದ್ದುಗೊಳಿಸಬೇಕೇ?' : 'Confirm Ticket Cancellation'}
              </h3>
              <p className="text-xs font-bold text-slate-300 leading-relaxed">
                {language === 'kn' 
                  ? `ಪಿಎನ್‌ಆರ್ ${ticket.pnr} ನ ಕಾಯ್ದಿರಿಸುವಿಕೆಯನ್ನು ರದ್ದುಗೊಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುತ್ತೀರಾ?` 
                  : `Are you sure you want to cancel your bus ticket booking for PNR ${ticket.pnr}?`
                }
              </p>
            </div>

            <div className="p-4 rounded-2xl bg-slate-800 border border-slate-700 text-left text-xs font-semibold space-y-1.5 text-slate-300">
              <div className="flex justify-between">
                <span>{language === 'kn' ? 'ಪಾವತಿಸಿದ ಮೊತ್ತ' : 'Amount Paid'}</span>
                <span className="font-mono text-white font-black">₹{ticket.amountPaid || ticket.amount || 0}</span>
              </div>
              <div className="flex justify-between text-emerald-400 font-bold">
                <span>{language === 'kn' ? 'ತತ್ಕ್ಷಣದ ರಿಫಂಡ್ (೧೦೦%)' : 'Instant Refund (100%)'}</span>
                <span className="font-mono font-black">₹{ticket.amountPaid || ticket.amount || 0}</span>
              </div>
              <p className="text-[10px] text-slate-400 pt-1.5 border-t border-slate-700 mt-1">
                ✓ {language === 'kn' ? 'ರಿಫಂಡ್ ಹಣವು ೨೪ ಗಂಟೆಗಳ ಒಳಗೆ ಮೂಲ ಪಾವತಿ ಮೂಲಕ್ಕೆ ತಲುಪುತ್ತದೆ.' : 'Refund will be credited to original payment source within 24 hours.'}
              </p>
            </div>

            <div className="flex gap-3 pt-2">
              <button
                onClick={() => {
                  if (cancelUserTicket) {
                    cancelUserTicket(ticket.pnr || ticket.bookingId);
                  }
                  setIsCancelled(true);
                  setShowCancelModal(false);
                }}
                className="flex-1 py-3 bg-red-600 hover:bg-red-500 text-white rounded-xl text-xs font-black cursor-pointer shadow-lg transition-all"
              >
                {language === 'kn' ? 'ಹೌದು, ಟಿಕೆಟ್ ರದ್ದುಗೊಳಿಸಿ' : 'Yes, Cancel Ticket'}
              </button>
              <button
                onClick={() => setShowCancelModal(false)}
                className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-black cursor-pointer border border-slate-700 transition-all"
              >
                {language === 'kn' ? 'ಟಿಕೆಟ್ ಇರಿಸಿಕೊಳ್ಳಿ' : 'Keep Booking'}
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
